Add support for docker!
I had to make some changes to the flow_warp Makefile (switch python to python3, change cuda arch from sm_52 to sm_61 and add a build flag to fix a undefined symbol error)

```
tensorflow.python.framework.errors_impl.NotFoundError: /root/ATEN/ops/build/flow_warp.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
```

Feel free to make any changes or completely drop it, figured it may help some other people get a head start and skip over build issues.